# Generated by Django 3.2.5 on 2021-07-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_url_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
